spring:
  application:
    name: catalog-service

# configure tomcat server
server:
  port: 9001
  tomcat:
    connection-timeout: 2s # default: 20s
    keep-alive-timeout: 15s
    threads:
      max: 50 # default: 200
      min-spare: 5 # min thread always be running default: 10

polar:
  greeting: Welcome to the book catalog!
  testData:
    enabled: false
